### ISSUE TITLE
Broadening appeal for the lessons so that PI will find and use these

### ISSUE THREAD

**Issue by malvikasharan** [carpentries-incubator/managing-computational-projects#21]
## Summary

- Senior researchers don't engage with these kinds of resources, what can we do to broaded the scope and integrate some aspects that PI would like to actually use this lesson?

**Comment by malvikasharan** [comment]
@ha0ye's comment
> how to broaden the appeal to PIs or more senior researchers: I often use an empowerment or "improve the rigor/efficiency of your lab" angle.

Comment by Julian Colomb: Biomedical scientist mostly want to do science, not manage anything, even less a computational project.

**Comment by jcolomb** [comment]
what about naming this:
 "Digital/open science tools facilitating team work in the lab"

**Comment by jcolomb** [comment]
what about:  

- data science for bio-medical researchers 1: basics
- data science for bio-medical researchers 2: machine learning
