### ISSUE TITLE
The Section on Tests is Missing

### ISSUE THREAD

**Issue by LydiaFrance** [carpentries-incubator/managing-computational-projects#29]
In this [file](https://github.com/carpentries-incubator/managing-computational-projects/blob/3c9e4d01ee77261b381afbbef88665aa949747b1/_episodes/05-implementation.md) the section on Tests is missing. Most of the content can be found form the Turing Way.

**Comment by malvikasharan** [comment]
This has been addressed in the Implementation episode.
