### ISSUE TITLE
Explictly add File Tree Template

### ISSUE THREAD

**Issue by LydiaFrance** [carpentries-incubator/managing-computational-projects#38]
The GinTonic directory is a useful example, add it to the Setup episode. 

https://gin-tonic.netlify.app/standard/

**Comment by yannickwurm** [comment]
FYI, we use something along these lines 
 https://github.com/wurmlab/templates/blob/master/project_structures.md
which is derived from https://www.ncbi.nlm.nih.gov/labs/pmc/articles/PMC2709440/
