### ISSUE TITLE
jargon terms

### ISSUE THREAD

**Issue by jcolomb** [carpentries-incubator/managing-computational-projects#41]
Here is a list of terms that sounds like jargon to me, it might be good to define them at the start if one wants to use them. (or use a glossary one can link to)

"data science"
"computational project" (isn't any data analysis a computational project, if so, isn't any project a computational project ?)

**Comment by malvikasharan** [comment]
Good catch @jcolomb. Thank you for this issue. Keeping this issue open for the review sprint so that one of the reviewers could pick it up and address them in the introduction episode.

**Comment by malvikasharan** [comment]
@jcolomb I have included "jargon busting" section here: https://carpentries-incubator.github.io/managing-computational-projects/01-introduction/index.html

These terms will also be discussed in details in this masterclass: https://carpentries-incubator.github.io/data-science-ai-senior-researchers/
