### ISSUE TITLE
Episode 1: Introduction

### ISSUE THREAD

**Issue by malvikasharan** [carpentries-incubator/managing-computational-projects#43]
- Introduction: Data Science for Biomedical Scientists Project
- HackMD: https://hackmd.io/@turingway/r1I-7J_H5

**Comment by jcolomb** [comment]
- [ ] intro too much about ML/AI
- [ ] data science intro
- [ ] explain why any project can be a computational project
- [ ] maybe add a section at the end for people wanting to know about AI





target audience well defined

**Comment by jcolomb** [comment]
text I erased from lesson 2, because fitting probably here (will add to lesson 1 later):

- [ ] Computational methods might indeed be as complex as a neural network, but even statistical tests and producing figures for a publication require data science and coding methods.
