### ISSUE TITLE
Episode 2: Starting with the scientific process

### ISSUE THREAD

**Issue by malvikasharan** [carpentries-incubator/managing-computational-projects#44]
HackMD: https://hackmd.io/@turingway/HJjT7kdBq

**Comment by jcolomb** [comment]
we are rewriting making it shorter (maybe) organisation:
any research project is a computational project
to make the research better is the goal of this course: that is 

- reproducibility
- improved efficiency
- easier collaboration
- better/more appropriate stats
- prettier/ more informative graphs 

for each point, we want to explain the issue and give some best practice/link to the course content itself.

**Comment by mlagisz** [comment]
Also removing redundant/confusing figures (taken from publications, without context)

**Comment by malvikasharan** [comment]
@all-contributors please add @jcolomb for idea, review and content

**Comment by malvikasharan** [comment]
@all-contributors please add @mlagisz for idea, review and content
