### ISSUE TITLE
Episode 4: Research Data Management

### ISSUE THREAD

**Issue by malvikasharan** [carpentries-incubator/managing-computational-projects#46]
HackMD: https://hackmd.io/@turingway/H1uSVkOHc

**Comment by jcolomb** [comment]
version control needs to come here, nothing to do with openness
again specificity of computational projects?

computational analysis:
- think computer readable data format (tidy spreadsheets)
- metadata
- avoid manual data wrangling: no copy-paste, no use the data acquisition software for analysis, start from raw data.
- Plan for code (text) management (file name, version control, ...)

**Comment by jcolomb** [comment]
to Include change as a new PR,
