### ISSUE TITLE
Episode 8: Implementing tools and methods

### ISSUE THREAD

**Issue by malvikasharan** [carpentries-incubator/managing-computational-projects#50]
HackMD: https://hackmd.io/@turingway/rJQ8UJdBc

**Comment by jcolomb** [comment]
- project management and code quality should be in 2 different chapters
- code quality part is much too long, "this course is not about writing code" 
- it should also be much more basic, based on provenance issue:
    - code is run from start to end, one can comment out sections, but then that version need to be saved with the figure.
    - reproducible reports: if possible add variables used, or script version in the resulting pdf

**Comment by jcolomb** [comment]
if code needs to be more basic: need general discussion #87 the other things were implemented
