### ISSUE TITLE
Migrate this lesson on the new infrastructure

### ISSUE THREAD

**Issue by malvikasharan** [carpentries-incubator/managing-computational-projects#67]
After a conversation with Toby, need to check with @zkamvar to help migrate this in July. 

We have a few open PR that @jcolomb and I will work to merge.

**Comment by jcolomb** [comment]
All merged or closed, we can go ahead with migration. (unresolved points in PR were added in issues)

**Comment by zkamvar** [comment]
Hi all, 

I apologise, but this may be delayed until after August: https://github.com/carpentries/workbench/discussions/22

**Comment by jcolomb** [comment]
Is it still in the agenda, we want the current pull request done, though/right?

**Comment by jcolomb** [comment]
@zkamvar We could do that now, if you have some time.

**Comment by zkamvar** [comment]
Hi @jcolomb,

Thank you for reminding me about this and sorry for the late reply. Would you be okay to have the transition take place on 06 February? I will be transitioning the [beta phase repositories](https://carpentries.github.io/workbench/beta-phase.html#lessons-currently-in-the-beta-phase) then, so it would be a natural step for me to take. 

I'll add your repo to the [carpentries/lesson-transition] today and test it out.

**Comment by jcolomb** [comment]
6h is a late reply ? we were indeed still merging stuff until yesterday. I think 6th of February is good.

**Comment by zkamvar** [comment]
I apologise that I wasn't able to get to this today. I will attempt tomorrow.

**Comment by jcolomb** [comment]
any new schedule for this?

**Comment by zkamvar** [comment]
I'm starting to sound like a broken record. Unfortunately, I'm going to have to push this back (too much on my plate, unfortunately). If you are okay, I'd like to do it on Monday.

**Comment by jcolomb** [comment]
it would be fantastic!

**Comment by zkamvar** [comment]
I have created a preview at https://github.com/fishtree-attempt/managing-computational-projects     
with the site available here: https://fishtree-attempt.github.io/managing-computational-projects/

I have not yet converted this in place for two reasons:

 1. #85 is still open (and will need to be redone after the transition)
 2. There are 17 people with write access to this particular repository who will **need to [re-clone](https://carpentries.github.io/workbench/beta-phase.html#updating-clone) (and, if necessary, [re-fork](https://carpentries.github.io/workbench/faq.html#update-fork-from-styles)) the repository after the transition**. I have written up some of [what to expect after the transition](https://carpentries.github.io/workbench/beta-phase.html#beta) (though be mindful that incubator repositories will not have the two-site setup). The folks who currently have write-access to the repository are: 
    - @maneesha
    - @jcolomb
    - @kasra-hosseini
    - @zkamvar
    - @arronlacey
    - @malvikasharan
    - @fedenanni
    - @tobyhodges
    - @mlagisz
    - @MCMaurer
    - @ErinBecker
    - @aldenc
    - @selgebali
    - @SaraVilla
    - @EKaroune
    - @carpentries-bot
    - @LydiaFrance    
    
I want to make sure everyone who has write-access is aware of the fact that they will need to update their local clones, because while I will be protecting the main branch, if someone is determined enough, they can accidentally merge the old lesson into the `gh-pages` branch.

@jcolomb let me know once #85 is merged and I will make the transition. Sorry again for the runaround.

**Comment by jcolomb** [comment]
we will re-add #85 by hand later on. closing it so you feel safe :)
@malvika, best may be to revoke write access, so we make sure people start fresh ?

**Comment by tobyhodges** [comment]
Note that six of the names listed above had access via their ownership of the `carpentries-incubator` GitHub organisation itself. 

@jcolomb it looks like you tagged the wrong Malvika @malvikasharan

**Comment by zkamvar** [comment]
Note: for real, I am going to do the conversion tomorrow. I had to do [a little bit of clean up for your lesson](https://github.com/carpentries/lesson-transition/blob/main/carpentries-incubator/managing-computational-projects.R) (no need for you to do anything) and I wanted to test the non-beta phase transition: https://github.com/fishtree-attempt/znk-transition-test
once more to make sure it was cromulent. 

All is good to go for the transition tomorrow. I will send a message to this thread, reset permissions, make the transition and then give admin permissions to @jcolomb and @malvikasharan so they can begin re-adding folks when they are ready. 

Here are some resources in the meantime:

1. What you can expect from the transition 📹: https://carpentries.github.io/workbench/beta-phase.html#beta
1. How to update your local clone 💻: https://carpentries.github.io/workbench/beta-phase.html#updating-clone
1. How to update (delete) your fork (if you have one) 📹: https://carpentries.github.io/workbench/faq.html#update-fork-from-styles

**Comment by zkamvar** [comment]
This lesson will be converted to use [The Carpentries Workbench][workbench]
To prevent accidental reversion of the changes, we are temporarily revoking
write access for all collaborators on this lesson:

 - [ ] @jcolomb (admin)
 - [ ] @kasra-hosseini (maintain)
 - [ ] @arronlacey (admin)
 - [ ] @malvikasharan (admin)
 - [ ] @fedenanni (admin)
 - [ ] @mlagisz (push)
 - [ ] @aldenc (maintain)
 - [ ] @selgebali (maintain)
 - [ ] @SaraVilla (maintain)
 - [ ] @EKaroune (maintain)
 - [ ] @LydiaFrance (admin)

If you no longer wish to have write access to this repository, you do not
need to do anything further.

1. What you can expect from the transition 📹: https://carpentries.github.io/workbench/beta-phase.html#beta
2. How to update your local clone 💻: https://carpentries.github.io/workbench/beta-phase.html#updating-clone
3. How to update (delete) your fork (if you have one) 📹: https://carpentries.github.io/workbench/faq.html#update-fork-from-styles

If you wish to regain write access, please re-clone the repository on your machine and
then comment here with `I am ready for write access :rocket:` and the
admin maintainer of this repository will restore your permissions.

If you have any questions, please reply here and tag @zkamvar

[workbench]: https://carpentries.github.io/workbench

**Comment by zkamvar** [comment]
The deed is done. @jcolomb and @malvikasharan, the infrastructure takes a few minutes to bootstrap the first time, but as contributors comment here, you have admin rights and should be able to grant them access to this lesson. 

Thank you for your patience on this!

**Comment by zkamvar** [comment]
The Workbench site is now live:

https://carpentries-incubator.github.io/managing-computational-projects/

There is a `legacy/gh-pages` branch that is locked and contains the old, untouched version of the lesson. Feel free to delete this if you do not wish to hang on to it anymore.

**Comment by zkamvar** [comment]
For reference, here is [a map of commits that were changed during the transition](https://github.com/carpentries/lesson-transition/blob/e5fc4ff9e810e6bda9ebc2730d55f9639fc9177d/release/carpentries-incubator/managing-computational-projects-commit-map.hash).

**Comment by malvikasharan** [comment]
Brilliant stuff @zkamvar 💐💐💐💐

Thank you for keeping track of this among many many repo that you are offering your time and services to. 
Thanks @jcolomb and @tobyhodges for coordinating this update. ❤️

**Comment by jcolomb** [comment]
hey. The new template looks much prettier to me :)

could not find the doc on how to preview locally, `make serve` does not work anymore...

**Comment by tobyhodges** [comment]
@jcolomb the Workbench lesson infrastructure is documented at https://carpentries.github.io/sandpaper-docs/ Here is the section about how to build and serve the lesson locally: https://carpentries.github.io/sandpaper-docs/introduction.html#preview

**Comment by jcolomb** [comment]
I used https://carpentries.github.io/workbench/ looks more general ;).

looking for other things to fix...
