### ISSUE TITLE
Discuss the episodes order and content

### ISSUE THREAD

**Issue by jcolomb** [carpentries-incubator/managing-computational-projects#73]
Several chapters are still empty, other may need to be split. Here is a new sessions proposal:

1. Introduction
2. Motivations and benefits
3. Setting up a project
4. Data workflow (RDM)
5. Project management
6. Data analysis (p-hacking, steps)
7. Coding: basics and documentation
8. Code management: review and tests
9. Publication and open science

this would erase the selection episode completely. One need to discuss whether to keep the long (new) chapter on data wrangling, if yes, should it be its own chapter (between 6 and 7 in this proposal).

**Comment by jcolomb** [comment]
version control episode before or after RDM one

**Comment by jcolomb** [comment]
make 7 (Coding: basics and documentation) very short and link to extra ?

**Comment by malvikasharan** [comment]
Notes from discussion:

- Version control can go before RDM.
- Open science can be introduced in Set up and then we sprinkle open science practices in each lesson
- Add data science additionality in the end of each lesson #76 
- Version control as it's own chapter
- Maybe move open science to all chapters?

**Comment by malvikasharan** [comment]
Create a chapter to list of tools as suggestion and specific ones discussed in the chapter.

**Comment by malvikasharan** [comment]
HackMd where we will discuss format: https://hackmd.io/RT3l5v2ZTjCwCteEDUdl5A

**Comment by jcolomb** [comment]
mostly done via #78, what was not done got new issues
