### ISSUE TITLE
Add exercises: build a research repository on github/gitlab

### ISSUE THREAD

**Issue by jcolomb** [carpentries-incubator/managing-computational-projects#79]
I am wondering whether we could/should add exercises implementing what we teach using GitHub. (creating a repo, having a readme file with all info needed, a little bit of git to push that changes, creating issues, ...)  

I will try to include that.

**Comment by mlagisz** [comment]
great idea

**Comment by jcolomb** [comment]
codeberg.org may be a even better place.
